# Generated by Django 2.2 on 2019-05-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0002_auto_20190528_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='SewaHaru',
        ),
    ]
