# Generated by Django 2.2 on 2019-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0003_auto_20190528_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuchanaItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suchana_photo_name', models.CharField(max_length=32)),
                ('suchana_photo_description', models.TextField(max_length=60)),
                ('suchana_photo', models.ImageField(blank=True, null=True, upload_to='suchana')),
            ],
        ),
    ]
