# Generated by Django 2.2 on 2019-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0004_suchanaitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewaharu',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='sewaharu',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
