# Generated by Django 2.2 on 2019-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0009_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchanaphotogallery',
            name='descriptionOfImage1',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='suchanaphotogallery',
            name='descriptionOfImage2',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='suchanaphotogallery',
            name='descriptionOfImage3',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='suchanaphotogallery',
            name='descriptionOfImage4',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='suchanaphotogallery',
            name='descriptionOfImage5',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='headline',
            name='headline_topic',
            field=models.TextField(max_length=2000),
        ),
    ]
