# Generated by Django 2.2 on 2019-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0010_auto_20190530_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuchanaPhotoGallery',
            new_name='PhotoGallery',
        ),
    ]
