# Generated by Django 2.2 on 2019-05-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0011_auto_20190530_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SewaHaru',
        ),
    ]
