# Generated by Django 2.2.1 on 2019-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0012_delete_sewaharu'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=100)),
                ('website', models.TextField(max_length=100)),
            ],
        ),
    ]
