# Generated by Django 2.2.1 on 2019-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0013_organizationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaupalikaBare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jesthaNagarik', models.TextField(max_length=20)),
                ('bidhuwa', models.TextField(max_length=100)),
                ('mahila', models.TextField(max_length=100)),
                ('aapanga', models.TextField(max_length=100)),
                ('dalit', models.TextField(max_length=100)),
                ('balbalika', models.TextField(max_length=100)),
            ],
        ),
    ]
