# Generated by Django 2.2.1 on 2019-06-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0015_auto_20190601_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='heading',
            new_name='Suchana1_heading',
        ),
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='suchana_photo',
            new_name='Suchana1_suchana_photo',
        ),
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='suchana_photo_description',
            new_name='Suchana1_suchana_photo_description',
        ),
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='suchana_photo_name',
            new_name='Suchana1_suchana_photo_name',
        ),
    ]
