# Generated by Django 2.2.1 on 2019-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0019_auto_20190608_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janapratinidhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('अध्यक्ष_नाम', models.CharField(default='Title', max_length=322)),
                ('Sachip_photo_phonenumber', models.TextField(blank=True, default='Title', max_length=200, null=True)),
                ('उपाध्यक्ष_नाम', models.CharField(default='Title', max_length=322)),
                ('उपाध्यक्ष_photo_phonenumber', models.TextField(blank=True, default='Title', max_length=200, null=True)),
                ('प्रमुख_प्रशासकीय_नाम', models.CharField(default='Title', max_length=322)),
                ('प्रमुख_प्रशासकीय_phonenumber', models.TextField(blank=True, default='Title', max_length=200, null=True)),
                ('सूचना_तथा_संचार_प्रविधि_अधिकृत_नाम', models.CharField(default='Title', max_length=322)),
                ('सूचना_तथा_संचार_प्रविधि_अधिकृत_phonenumber', models.TextField(blank=True, default='Title', max_length=200, null=True)),
            ],
        ),
    ]
