# Generated by Django 2.2.1 on 2019-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0020_janapratinidhi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='अध्यक्ष_नाम',
            new_name='aadxya_name',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='Sachip_photo_phonenumber',
            new_name='aadxya_phonenumber',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='उपाध्यक्ष_नाम',
            new_name='pramukh_prasasakya_name',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='उपाध्यक्ष_photo_phonenumber',
            new_name='pramukh_prasasakya_phonenumber',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='प्रमुख_प्रशासकीय_नाम',
            new_name='suchana_tatha_sanchar_pratinidhi_name',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='प्रमुख_प्रशासकीय_phonenumber',
            new_name='suchana_tatha_sanchar_pratinidhi_phonenumber',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='सूचना_तथा_संचार_प्रविधि_अधिकृत_नाम',
            new_name='upadaxya_name',
        ),
        migrations.RenameField(
            model_name='janapratinidhi',
            old_name='सूचना_तथा_संचार_प्रविधि_अधिकृत_phonenumber',
            new_name='upadaxya_phonenumber',
        ),
        migrations.AddField(
            model_name='janapratinidhi',
            name='aadxya_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='janapratinidhi',
            name='pramukh_prasasakya_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='janapratinidhi',
            name='suchana_tatha_sanchar_pratinidhi_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='janapratinidhi',
            name='upadaxya_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
