# Generated by Django 2.2.1 on 2019-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0021_auto_20190610_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='wadaNumber',
            field=models.IntegerField(default=6, max_length=100),
            preserve_default=False,
        ),
    ]
