# Generated by Django 2.2.2 on 2019-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0023_auto_20190611_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='title_of_photo1',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_of_photo2',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_of_photo3',
            field=models.CharField(default=3, max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_of_photo4',
            field=models.CharField(default=4, max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_of_photo5',
            field=models.CharField(default=5, max_length=200),
        ),
    ]
