# Generated by Django 2.2.2 on 2019-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0025_auto_20190622_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallery',
            old_name='descriptionOfImage',
            new_name='descriptionOfImage1',
        ),
        migrations.RenameField(
            model_name='photogallery',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='title_of_photo',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='descriptionOfImage2',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='descriptionOfImage3',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='descriptionOfImage4',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='descriptionOfImage5',
            field=models.TextField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
