# Generated by Django 2.2.2 on 2019-06-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0026_auto_20190622_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='Suchana1_suchana_photo_description',
            new_name='Suchana1_suchana_info',
        ),
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='Suchana2_suchana_photo_description',
            new_name='Suchana2_suchana_info',
        ),
        migrations.RenameField(
            model_name='suchanaitems',
            old_name='Suchana3_suchana_photo_description',
            new_name='Suchana3_suchana_info',
        ),
    ]
