# Generated by Django 2.2.2 on 2019-06-23 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_site_app', '0027_auto_20190623_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchanaitems',
            name='Suchana_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
